#!/bin/bash
sudo su
apt update -y
apt install -y docker.io python3-pip maven unzip wget
systemctl start docker
systemctl enable docker

# Run Nexus container
docker run -d --name nexus -p 8081:8081 sonatype/nexus3:latest

# Install gdown
pip3 install gdown --break-system-packages

# Download project zip from Google Drive
python3 -m gdown --id 1Gx63BuODDFga8JkBRbouHVzW07TS6UHQ -O /root/JAR-WAR-SNAPSHOTS.zip

# Unzip the project
unzip -o /root/JAR-WAR-SNAPSHOTS.zip -d /root/

# Create Maven settings.xml for Nexus
mkdir -p ~/.m2
cat <<EOF >~/.m2/settings.xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
          https://maven.apache.org/xsd/settings-1.0.0.xsd">

  <servers>
    <server>
      <id>maven-snapshots</id>
      <username>admin</username>
      <password>faisal</password>
    </server>
  </servers>

</settings>
EOF
