#!/bin/bash
sudo su
apt update -y
apt install -y docker.io unzip wget
systemctl start docker
systemctl enable docker

# Run SonarQube container
docker run -d --name sonarqube -p 9000:9000 sonarqube:community

# Download project zip from Google Drive
wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1wJ-Da8G7BqJ3UGLEgRSzk6HkF1hChXpY" -O /root/website.zip

# Unzip the file
unzip -o /root/website.zip -d /root/
