#!/bin/bash
sudo su
apt update -y
apt install -y gnupg software-properties-common curl unzip lsb-release wget

# Install AWS CLI
cd /tmp
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

# Install Terraform
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
| sudo tee /etc/apt/sources.list.d/hashicorp.list
apt-get update
apt-get install terraform -y

# Download the tf file directly (public Google Drive link)
wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1vt0ZpqOldiiZKaRVTi1eeQwmNoWdQaBV" -O /root/ec2.website.tf
