#!/bin/bash
sudo su
apt update -y
apt install -y apache2 unzip wget
systemctl start apache2
systemctl enable apache2

# Download the zip directly (public Google Drive link)
wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1H9RaSCEx1pvBupx2qcDvcN1E7YLdcl2B" -O neogym.zip

# Unzip the file
unzip -o neogym.zip

# Copy files to Apache web directory
cp -r neogym-html/* /var/www/html/

# Restart Apache
systemctl restart apache2
