#!/bin/bash
sudo su
apt update -y
apt install -y openjdk-21-jdk unzip wget curl

# Add Jenkins repo and key
sudo wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

# Update and install Jenkins
apt update -y
apt install -y jenkins
systemctl enable jenkins
systemctl start jenkins

# Install AWS CLI
cd /tmp
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

# Restart Jenkins
systemctl restart jenkins
