#!/bin/bash
sudo su
apt update -y
apt install -y docker.io
systemctl start docker
systemctl enable docker

# Run Jenkins container
docker run -d --name jenkins -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts
